version: '3'
services:

  nginx:
    image: nginx:stable-alpine
    container_name: nginx
    restart: always
    volumes:
      - ./typecho:/app
      - ./typecho.conf:/etc/nginx/conf.d/default.conf
      - logs:/var/log/nginx      
#      - ./site.conf:/etc/nginx/conf.d/site.conf
#      - ./typecho/config.inc.php:/app/config.inc.php
    expose: 
      - '80'
      - '443'
    ports:
      - "80:80"
      - "443:443"
    links:
      - php-fpm
    depends_on:
      - php-fpm

  php-fpm:
    image: faintghost/php-fpm
    container_name: php-fpm
    restart: always
    volumes:
      - ./typecho:/app
    links:
      - db
    depends_on:
      - db

  db:
    image: mysql:5.7.21
    container_name: mysql
    restart: always
    expose: 
      - '3306'
    ports:
      - "3306:3306"
    volumes:
      - ./mysql:/var/lib/mysql
      - logs:/var/logs/mysql
    env_file:
      - mysql.env

volumes:
  logs: